name: Type Check

on:
  push:

jobs:
  type-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'

      - name: Install
        run: |
          yarn

      - name: Type Check
        run: |
          yarn type:check
